routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Controller@index')->name('index');
Route::get('/prueba','Controller@prueba');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cerrarSesion', 'HomeController@cerrarSesion')->name('cerrarSesion');

Route::prefix('panel-admin')->middleware(['auth', 'accesoPanelAdministrativo'])->group(function () {
    Route::resource('categorias', 'CategoriasController');
    // Route::get('categorias', 'CategoriasController@index')->name('categorias.index');
    // Route::get('categorias/create', 'CategoriasController@create')->name('categorias.create');
    // Route::post('categorias', 'CategoriasController@store')->name('categorias.store');
    // Route::get('categorias/{id}', 'CategoriasConroller@show')->name('categorias.show');
    // Route::get('categorias/{id}/edit', 'CategoriasController@edit')->name('categorias.edit');
    // Route::put('categorias/{id}', 'CategoriasController@update')->name('categorias.update');
    // Route::delete('categorias/{id}', 'CategoriasController@destroy')->name('categorias.destroy');
    Route::resource('categorias.subcategorias', 'SubcategoriasController')->parameters(['categorias' => 'categorias:id']);
    Route::resource('categorias.subcategorias.productos', 'ProductosController');
});

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Storage;
use Config;

class Producto extends Model
{
    use SoftDeletes;

    public function subcategoria() {
        return $this->belongsTo(Subcategoria::class);
    }

    public function url() {
        $s3 = Storage::disk('s3');
        $cliente = $s3->getDriver()->getAdapter()->getClient();
        $expiracion = '+15 seconds';
        $comando = $cliente->getCommand('GetObject', [
            'Bucket' => Config::get('filesystems.disks.s3.bucket'),
            'Key' => $this->uri
        ]);
        $res = $cliente->createPresignedRequest($comando, $expiracion);
        return (string) $res->getUri();
    }

    public function estaEnDescuento() {
        return true;
    }
}

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subcategoria;
use App\Categoria;
use App\Producto;
use Validator;
use Session;
use App\Traits\TraitNotificaciones;
use App\Traits\TraitImagenes;
use Storage;
use Intervention\Image\ImageManagerStatic as Image;



class ProductosController extends Controller
{
    use TraitNotificaciones, TraitImagenes;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $subcategoria = 2;
        $subcategoria = Subcategoria::find($subcategoria);

        $categoria = Categoria::find($subcategoria->categoria_id);
        $coleccion = $subcategoria->productos()->withTrashed()->orderBy('created_at','DESC')->get();

        return view('panel-admin.productos.index')
            ->with('categoria', $categoria->id)
            ->with('subcategoria',$subcategoria->id)
            ->with('coleccion', $coleccion);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$categoria,$subcategoria)
    {
        //

         $validator = Validator::make($request->all(), [
            'nombre' => 'required|string|max:255',
            'precio' => 'required|string|max:255',
            'descripcion' => 'required|string',
            'imagen' => 'nullable|image',
        ]);

        if ($validator->fails()) {
           $this->notificacionError();

            return redirect()->route('categorias.subcategorias.productos.create',[$categoria],[$subcategoria])
                ->withErrors($validator)
                ->withInput();
        }

        $objeto = new Producto;
        $objeto->subcategoria_id = $subcategoria;
        $objeto->nombre = filter_var($request->nombre, FILTER_SANITIZE_STRING);
        $objeto->descripcion=$request->descripcion;
        $objeto->uri = (isset($request->imagen) && !empty($request->imagen)) ? $this->guardarImagen($request->imagen) : null;
        $objeto->precio=filter_var($request->precio, FILTER_SANITIZE_STRING);
        $objeto->save();

       // $this->notificacionSuccess();

        return redirect()->route('categorias.subcategorias.productos.index', [$categoria,$subcategoria]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($categoria,$subcategoria,$id)
    {
        //
        $objeto = Producto::find($id);

        return view('panel-admin.productos.edit')
            ->with('categoria', $categoria)
            ->with('subcategoria',$subcategoria)
            ->with('objeto', $objeto);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $categoria, $subcategoria, $id)
    {
        //

         $validator = Validator::make($request->all(), [
            'nombre' => 'required|string|max:255',
            'precio' => 'required|string|max:255',
            'descripcion' => 'required|string',
            'uri' => 'nullable|string|max:255',
        ]);

        if ($validator->fails()) {
           $this->notificacionError();

            return redirect()->route('categorias.subcategorias.productos.edit',[$categoria],[$subcategoria])
                ->withErrors($validator)
                ->withInput();
        }

        $objeto = Producto::find($id);

        $objeto->nombre = filter_var($request->nombre, FILTER_SANITIZE_STRING);
        $objeto->descripcion=$request->descripcion;
        $objeto->precio=filter_var($request->precio, FILTER_SANITIZE_STRING);
        $objeto->uri = isset($request->uri) && !empty($request->uri) ? filter_var($request->uri, FILTER_SANITIZE_STRING) : null;
        $objeto->save();

       // $this->notificacionSuccess();

        return redirect()->route('categorias.subcategorias.productos.index', [$categoria,$subcategoria]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($categoria,$subcategoria,$id)
    {
        //
        $objeto = Producto::withTrashed()->find($id);

        if($objeto->deleted_at) {
            $objeto->deleted_at = null;
            $objeto->save();
           // $this->notificacionSuccessReactivacion();
        } else {
            $objeto->delete();
            //$this->notificacionSuccessEliminacion();
        }

        return redirect()->route('categorias.subcategorias.productos.index', [$categoria,$subcategoria]);

    }

     private function formatoImagen($imagen)
    {
        $img = Image::make($imagen);
        $img->resize(700, null, function ($constraint) {
            $constraint->aspectRatio();
        });
        $img = $img->stream()->__toString();
        return $img;
    }


    public function ejemplosInnerJoin()
    {




    }











}

resources/views/panel-admin/productos/create.blade.php
@extends('layouts.admin')

@section('contenido')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/home">Panel</a></li>
    <li class="breadcrumb-item"><a href="/panel-admin/categorias">Administración Categorias</a></li>
    <li class="breadcrumb-item active" aria-current="page">Administración Subcategorias</li>

  </ol>
</nav>

<div class="card stacked-form">
    <div class="card-header ">
        <h4 class="card-title">Agregar subcategoria a {{$categoriaProvisional->nombre}}</h4>
    </div>
    <form method="POST" action="{{route('categorias.subcategorias.store', [$categoria])}}">
        @csrf
        <div class="card-body ">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                    value="{{old('nombre')}}" placeholder="Nombre..." required>
                @error('nombre')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label>URI</label>
                <input type="text" name="uri" class="form-control @error('uri') is-invalid @enderror"
                    value="{{old('uri')}}" placeholder="URI...">
                @error('uri')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-info">Guardar</button>
        </div>
    </form>
</div>
@endsection

resources/views/panel-admin/productos/edit.blade.php
@extends('layouts.admin')

@section('contenido')
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/home">Panel</a></li>
    <li class="breadcrumb-item"><a href="/panel-admin/categorias">Administración Categorias</a></li>
    <li class="breadcrumb-item active" aria-current="page">Administración Subcategorias</li>

  </ol>
</nav>

<div class="card stacked-form">
    <div class="card-header ">
        <h4 class="card-title">Editar</h4>
    </div>
    <form method="POST" action="{{route('categorias.subcategorias.productos.update', [$categoria,$subcategoria,$objeto->id])}}">
        @csrf
        @method('PUT')
        <div class="card-body ">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                    value="{{old('nombre', $objeto->nombre)}}" placeholder="Nombre..." required>
                @error('nombre')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>

             <div class="form-group">
                <label>Precio</label>
                <input type="number" step="any" name="precio" class="form-control @error('precio') is-invalid @enderror"
                    value="{{$objeto->precio}}" placeholder="Precio..." required>
                @error('precio')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>

            <div class="form-group">
                <label>Descripcion</label>
                <textarea name="descripcion" style="height:60px;" class="form-control @error('descripcion') is-invalid @enderror"
                     placeholder="Descripcion..." required>{{$objeto->descripcion}}</textarea>  
                @error('precio')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>


            <div class="form-group">
                <label>URI</label>
                <img src="{{$objeto->uri}}" class="img-fluid">
                @error('uri')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-info">Guardar</button>
        </div>
    </form>
</div>

<script src="//cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'descripcion' );
</script>
@endsection

resources/views/panel-admin/productos/index.blade.php
@extends('layouts.admin')

@section('contenido')


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/home">Panel</a></li>
    <li class="breadcrumb-item"><a href="/panel-admin/categorias">Administración Categorias</a></li>
    <li class="breadcrumb-item"><a href="/panel-admin/categorias/{{$categoria}}/subcategorias">Administración Subcategorias</a></li>
    <li class="breadcrumb-item active" aria-current="page">Administración Productos</li>

  </ol>
</nav>


<div class="card data-tables">
    <div class="card-body table-striped table-no-bordered table-hover dataTable dtr-inline table-full-width">
        <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
        </div>
        <div class="row m-5">
            <div class="col-md-4">
                <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-primary btn-block">Agregar</a>
            </div>
        </div>
        <div class="fresh-datatables">
            <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0"
                width="100%" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Descripcion</th>
                        <th class="disabled-sorting text-right">Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Productos</th>
                        <th class="disabled-sorting text-right">Actions</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($coleccion as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td><img src="{{$item->url()}}" class="img-fluid"></td>
                        <td>{{$item->nombre}}</td>
                        <td>${{number_format($item->precio,2)}}</td>
                        <td>
                            @php
                            echo $item->descripcion;
                            @endphp
                        </td>

                        <td class="text-right">
                            <a href="{{route('categorias.subcategorias.productos.edit', [$item->subcategoria->categoria->id, $item->subcategoria->id, $item->id])}}" class="btn btn-link btn-warning edit"><i
                                    class="fa fa-edit"></i></a>
                            <form method="POST" action="{{route('categorias.subcategorias.productos.destroy', [$item->subcategoria->categoria, $item->subcategoria, $item])}}" onsubmit="return confirm('¿Estas seguro que quieres eliminar a {{$item->nombre}}?');">
                                @csrf
                                @method('DELETE')
                                @if ($item->deleted_at)
                                <input type="submit" class="btn btn-info" value="Reactivar">
                                @else
                                <input type="submit" class="btn btn-danger" value="Borrar">
                                @endif

                            </form>
                            {{-- <a href="#" class="btn btn-link btn-danger remove"><i class="fa fa-times"></i></a> --}}
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>





<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Insertar Producto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form method="POST" action="{{route('categorias.subcategorias.productos.store', [$item->subcategoria->categoria, $item->subcategoria, $item])}}" enctype='multipart/form-data'>
        @csrf
        <div class="card-body ">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                    value="{{old('nombre')}}" placeholder="Nombre..." required>
                @error('nombre')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>

            <div class="form-group">
                <label>Precio</label>
                <input type="number" step="any" name="precio" class="form-control @error('precio') is-invalid @enderror"
                    value="{{old('precio')}}" placeholder="Precio..." required>
                @error('precio')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>

            <div class="form-group">
                <label>Descripcion</label>
                <textarea name="descripcion" style="height:60px;" class="form-control @error('descripcion') is-invalid @enderror"
                     placeholder="Descripcion..." required>{{old('descripcion')}}</textarea>
                @error('precio')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>


             <div class="form-group">
          <label>Imagen de Perfil  (1900x1200):</label><br>
             <div class="btn btn-primary">
                Seleccionar Imagen
                <input required id="uploadImage" accept="image/*"  type="file" name="imagen" onchange="PreviewImage();">

                  </div>
            @if($errors->has('imagen'))
            <span class="help-block text-danger">
                {{ $errors->first('imagen') }}
            </span>
            @endif
                  <img id="uploadPreview" class="img-fluid img-responsive" style="" />
        </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-info">Guardar</button>
        </div>
    </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


<script src="//cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'descripcion' );

    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };
</script>

@endsection