routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Controller@index')->name('index');
Route::get('/prueba','Controller@prueba');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cerrarSesion', 'HomeController@cerrarSesion')->name('cerrarSesion');

Route::prefix('panel-admin')->middleware(['auth', 'accesoPanelAdministrativo'])->group(function () {
    Route::resource('categorias', 'CategoriasController');
    // Route::get('categorias', 'CategoriasController@index')->name('categorias.index');
    // Route::get('categorias/create', 'CategoriasController@create')->name('categorias.create');
    // Route::post('categorias', 'CategoriasController@store')->name('categorias.store');
    // Route::get('categorias/{id}', 'CategoriasConroller@show')->name('categorias.show');
    // Route::get('categorias/{id}/edit', 'CategoriasController@edit')->name('categorias.edit');
    // Route::put('categorias/{id}', 'CategoriasController@update')->name('categorias.update');
    // Route::delete('categorias/{id}', 'CategoriasController@destroy')->name('categorias.destroy');
    Route::resource('categorias.subcategorias', 'SubcategoriasController')->parameters(['categorias' => 'categorias:id']);
    Route::resource('categorias.subcategorias.productos', 'ProductosController');
});

app/Subcategoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subcategoria extends Model
{
    use SoftDeletes;

    public function categoria() {
        return $this->belongsTo(Categoria::class);
    }

    public function productos() {
        return $this->hasMany(Producto::class);
    }
}

app/Http/Controllers/SubcategoriasController.php
<?php

namespace App\Http\Controllers;

use App\Traits\TraitNotificaciones;

use Illuminate\Http\Request;
use Validator;
use Session;
use App\Categoria;
use App\Subcategoria;

class SubcategoriasController extends Controller
{
    use TraitNotificaciones;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categoria = 1;
        $categoria = Categoria::find($categoria);
        $coleccion = $categoria->subcategorias()->withTrashed()->get();

        return view('panel-admin.subcategorias.index')
            ->with('categoria', $categoria->id)
            ->with('coleccion', $coleccion);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($categoria)
    {
        $categoriaProvisional=Categoria::find($categoria);
        return view('panel-admin.subcategorias.create')
            ->with('categoria', $categoria)->with('categoriaProvisional',$categoriaProvisional);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $categoria)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|string|max:255',
            'uri' => 'nullable|string|max:255',
        ]);

        if ($validator->fails()) {
           $this->notificacionError();

            return redirect()->route('categorias.subcategorias.create',[$categoria])
                ->withErrors($validator)
                ->withInput();
        }

        $objeto = new Subcategoria;
        $objeto->categoria_id = $categoria;
        $objeto->nombre = filter_var($request->nombre, FILTER_SANITIZE_STRING);
        $objeto->uri = isset($request->uri) && !empty($request->uri) ? filter_var($request->uri, FILTER_SANITIZE_STRING) : null;
        $objeto->save();

        $this->notificacionSuccess();

        return redirect()->route('categorias.subcategorias.index', [$categoria]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($categoria, $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($categoria, $id)
    {
        $objeto = Subcategoria::find($id);

        return view('panel-admin.subcategorias.edit')
            ->with('categoria', $categoria)
            ->with('objeto', $objeto);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $categoria, $id)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|string|max:255',
            'uri' => 'nullable|string|max:255',
        ]);

        if ($validator->fails()) {
           $this->notificacionError();

            return redirect()->route('categorias.create')
                ->withErrors($validator)
                ->withInput();
        }

        $objeto = Subcategoria::find($id);
        $objeto->nombre = filter_var($request->nombre, FILTER_SANITIZE_STRING);
        $objeto->uri = isset($request->uri) && !empty($request->uri) ? filter_var($request->uri, FILTER_SANITIZE_STRING) : null;
        $objeto->save();

        $this->notificacionSuccess();

        return redirect()->route('categorias.subcategorias.index', [$categoria]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($categoria, $id)
    {
        $objeto = Subcategoria::withTrashed()->find($id);

        if($objeto->deleted_at) {
            $objeto->deleted_at = null;
            $objeto->save();
            $this->notificacionSuccessReactivacion();
        } else {
            $objeto->delete();
            $this->notificacionSuccessEliminacion();
        }

        return redirect()->route('categorias.subcategorias.index', [$categoria]);
    }
}

resources/views/panel-admin/subcategorias/create.blade.php
@extends('layouts.admin')

@section('contenido')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/home">Panel</a></li>
    <li class="breadcrumb-item"><a href="/panel-admin/categorias">Administración Categorias</a></li>
    <li class="breadcrumb-item active" aria-current="page">Administración Subcategorias</li>

  </ol>
</nav>

<div class="card stacked-form">
    <div class="card-header ">
        <h4 class="card-title">Agregar subcategoria a {{$categoriaProvisional->nombre}}</h4>
    </div>
    <form method="POST" action="{{route('categorias.subcategorias.store', [$categoria])}}">
        @csrf
        <div class="card-body ">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                    value="{{old('nombre')}}" placeholder="Nombre..." required>
                @error('nombre')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label>URI</label>
                <input type="text" name="uri" class="form-control @error('uri') is-invalid @enderror"
                    value="{{old('uri')}}" placeholder="URI...">
                @error('uri')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-info">Guardar</button>
        </div>
    </form>
</div>
@endsection

resources/views/panel-admin/subcategorias/edit.blade.php
@extends('layouts.admin')

@section('contenido')
<div class="card stacked-form">
    <div class="card-header ">
        <h4 class="card-title">Editar</h4>
    </div>
    <form method="POST" action="{{route('categorias.subcategorias.update', [$categoria, $objeto->id])}}">
        @csrf
        @method('PUT')
        <div class="card-body ">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                    value="{{old('nombre', $objeto->nombre)}}" placeholder="Nombre..." required>
                @error('nombre')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label>URI</label>
                <input type="text" name="uri" class="form-control @error('uri') is-invalid @enderror"
                    value="{{old('uri', $objeto->uri)}}" placeholder="URI...">
                @error('uri')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-info">Guardar</button>
        </div>
    </form>
</div>
@endsection

resources/views/panel-admin/subcategorias/index.blade.php
@extends('layouts.admin')

@section('contenido')


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/home">Panel</a></li>
    <li class="breadcrumb-item"><a href="/panel-admin/categorias">Administración Categorias</a></li>
    <li class="breadcrumb-item active" aria-current="page">Administración Subcategorias</li>

  </ol>
</nav>


<div class="card data-tables">
    <div class="card-body table-striped table-no-bordered table-hover dataTable dtr-inline table-full-width">
        <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
        </div>
        <div class="row m-5">
            <div class="col-md-4">
                <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-primary btn-block">Agregar</a>
            </div>
        </div>
        <div class="fresh-datatables">
            <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0"
                width="100%" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Productos</th>
                        <th class="disabled-sorting text-right">Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Productos</th>
                        <th class="disabled-sorting text-right">Actions</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($coleccion as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td><img src="{{$item->uri}}" class="img-fluid"></td>
                        <td>{{$item->nombre}}</td>
                        <td>
                            <a href="/panel-admin/categorias/{{$categoria}}/subcategorias/{{$item->id}}/productos" class="btn btn-primary btn-block">Admn. Productos</a>
                        </td>
                        <td class="text-right">
                            <a href="{{route('categorias.subcategorias.edit', [$categoria, $item->id])}}" class="btn btn-link btn-warning edit"><i
                                    class="fa fa-edit"></i></a>
                            <form method="POST" action="{{route('categorias.subcategorias.destroy', [$categoria, $item->id])}}" onsubmit="return confirm('¿Estas seguro que quieres eliminar a {{$item->nombre}}?');">
                                @csrf
                                @method('DELETE')
                                @if ($item->deleted_at)
                                <input type="submit" class="btn btn-info" value="Reactivar">
                                @else
                                <input type="submit" class="btn btn-danger" value="Borrar">
                                @endif

                            </form>
                            {{-- <a href="#" class="btn btn-link btn-danger remove"><i class="fa fa-times"></i></a> --}}
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>





<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Insertar Subcategoria</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form method="POST" action="{{route('categorias.subcategorias.store', [$categoria])}}">
        @csrf
        <div class="card-body ">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                    value="{{old('nombre')}}" placeholder="Nombre..." required>
                @error('nombre')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label>URI</label>
                <input type="text" name="uri" class="form-control @error('uri') is-invalid @enderror"
                    value="{{old('uri')}}" placeholder="URI...">
                @error('uri')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-info">Guardar</button>
        </div>
    </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


@endsection